CESNET/ipfixcol

base/src/ipfix_message.c

This pull request features two fixes:
* ed1d686: due to a mistake in the number of ampersands, the row's element ID was determined as a comparison, rather than a bitwise AND. As such, the element IDs of enterprise-specific fields was always '1'.
* da469b0: we can use the fact that enterprise IDs (PENs) are non-zero for enterprise-specific fields to get rid of the ```has_ren``` variable, which simplifies the code.

Bug fixes for fields_get_field (base/src/ipfix_message.c)

---

base/headers/ipfixcol/utils.h
base/src/config.c
base/src/input/sctp/convert.c
base/src/input/tcp/convert.c
base/src/input/tcp/tcp_input.c
base/src/input/udp/convert.c
base/src/input/udp/udp_input.c
base/src/intermediate/anonymization/Crypto-PAn/panonymizer.c
base/src/intermediate/anonymization/Crypto-PAn/rijndael.c
base/src/intermediate/anonymization/anonymization_ip.c
base/src/intermediate/hooks/hooks.c
base/src/output_manager.c
base/src/storage/ipfix/ipfix_file.c
base/src/utils/utils.c

Several vulnerabilities have been fixed, mostly related to (potential) buffer overflows. To avoid repeating error-prone code for fixing every instance of `str(n)cpy`, I've implemented util-function `strncpy_safe` and replaced every instance of `str(n)cpy` with it.

Bunch of buffer overflow vulnerability fixes

---

base/src/config.c

This pull request is a follow-up for #17. Besides some textual changes, it merely improves the handling of XML comments in case no intermediate plugins are specified for loading in `startup.xml`.

config.c: Improved logging and accuracy in case of XML comments

---

tools/fbitdump/src/Configuration.cpp

During one of the later merging iterations, an error has been introduced that could cause a segfault when fbitdump was called with parameter `-m`.

fbitdump: fix for -m segfault

---

base/src/preprocessor.c
base/src/storage/forwarding/forwarding.c

The old version of `preprocessor_compute_crc` was copying more data than it should (using `memcpy`) and was rather error-prone. In addition, the produced output (`buff`) was just empty. The new version of `preprocessor_compute_crc` is much easier to read. Please let me know whether this matches your vision with regard to this function and provide me with feedback, if needed.

Refactoring of preprocessor_compute_crc

---

plugins/storage/fastbit/fastbit_element.cpp

In case an IE in a template has not been specified in `ipfix-elements.xml`, the function `get_type_from_xml` (fastbit_element.cpp) would return `NULL`. As such, the switch-statement in fastbit_table.cpp (`template_table::parse_template`) would not trigger the `UNKNOWN` or `default` cases, resulting in undefined behavior.

Invalid handling of unspecified IEs

---

base/headers/ipfixcol/utils.h
base/src/ipfixcol.c
base/src/utils/utils.c

Due to missing error handling functionality for `atoi`, I've implemented an improved version that is based on `strtol` with proper error handling. This avoids many potential errors when trying to start IPFIXcol with invalid parameters.

Improved IPFIXcol input parameter handling

---

tools/fbitdump/man/fbitdump.dbk
tools/fbitdump/src/Configuration.cpp
tools/fbitdump/src/Filter.cpp
tools/fbitdump/src/Utils.cpp
tools/fbitdump/src/Utils.h
tools/fbitdump/src/fbitdump.cpp

The handling of -N arguments by `fbitdump` has turned out to be rather fragile after the recent implementation of optional arguments. The reason for this is that if the (integer) number printing level indicator for -N is written with a white-space separator (e.g., `-N 5`), `5` would be treated as the query filter rather than the number printing level indicator.

fbitdump stability fixes: handling of -N arguments

---

tools/fbitexpire/src/Directory.cpp
tools/fbitexpire/src/PipeListener.cpp
tools/fbitexpire/src/PipeListener.h
tools/fbitexpire/src/fbitexpire.cpp

The problem is that a second `fbitexpire` process instance is not able to open the pipe. Both process instances are using the same (default) pipe. The observed behavior is also described in [1], for example. Also, pipes are now cleaned up when an `fbitexpire` daemon is killed.
[1] http://stackoverflow.com/questions/12636485/non-blocking-call-to-ofstreamopen

fbitexpire: fixed hanging pipe open

---

base/src/intermediate/anonymization/Crypto-PAn/panonymizer.c

We previously replaced all invocations of `strncpy` by `strncpy_safe`, to ensure safe String termination. In this particular case, however, this change results in decreased entropy (the last byte of the key is always zero). We therefore revert this change here.

Panonymizer.c: fixed previous improvement that results in decreased entropy

---

plugins/storage/fastbit/fastbit_element.cpp

Added a warning message in case no specification is found for an element that was converted from NetFlow v9 to IPFIX with the enterprise bit set.

Fastbit storage improvements

---

tools/fbitdump/src/DefaultPlugin.cpp
tools/fbitdump/src/Filter.cpp
tools/fbitdump/src/Filter.h

All compiler warnings were due to 'unused variables'.

fbitdump: fixed compiler warnings

---

base/src/utils/profiles/profiles.cpp

Please double-check this fix. The point is that the `for`-loop has to stop iterating once a `rootProfile` has been found.

utils/profiles/profiles.cpp: fixed resource leak

---

plugins/intermediate/geoip/configure.ac
plugins/intermediate/geoip/geoip.c
plugins/intermediate/profile_stats/configure.ac
plugins/intermediate/profiler/configure.ac
plugins/intermediate/stats/configure.ac
plugins/intermediate/uid/configure.ac

These fixes are mostly related to missing checks for libraries (especially `libxml`) and string concatenation errors for `CPPFLAGS`.

Various configure fixes for several plugins

---

base/src/output_manager.c

This is done to ensure uniqueness of each `statisticsFile` in case multiple collecting processes are active.

Output Manager/statisticsFile: add PID to filename

---

base/src/ipfixcol.c

This fix, which merely changes the order in which `daemon()` and `fork()` are called, makes sure that all collecting processes have the same parent process (which is not PID 1).

Daemonization: moved daemon() call to before fork

---

base/src/input/ipfix/ipfix_file.c

This commit fixes a bug that causes the following startup configuration not to be parsed correctly:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ipfix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">
<collectingProcess>
<name>TCP collector</name>
<fileReader>
<file>file:./ipfixcol/base/tests/ipfixcol_test/tests/ipfix_data/01-odid0.ipfix</file>
</fileReader>
<exportingProcess>File viewer</exportingProcess>
</collectingProcess>
<exportingProcess>
<name>File viewer</name>
<destination>
<name>File viewer</name>
<fileWriter>
<fileFormat>ipfix</fileFormat>
<file>file:./out.ipfix</file>
</fileWriter>
</destination>
</exportingProcess>
</ipfix>
```
Before, XML configuration file parsing would stop after the first child node within `<fileReader>`, which may be a comment, as in the provided …

IPFIX file input: fixed XML config file parsing bug

---

base/src/ipfixcol.c

This is done to be more in line with standard options in frequently-used tools. At this moment, only the following options are implemented:
* `--help`
* `--version`

IPFIXcol: implemented longopt support

---

tools/fbitdump/src/plugins/http_status_code.c

This issue was introduced in #87.

fbitdump/http_status_code: fixed uninitialized scalar variable

---

base/src/configurator.c

Fixed logging to be more consistent with other components

Configurator: fixed logging consistency

---

base/headers/ipfixcol/input.h
base/headers/ipfixcol/storage.h
base/src/intermediate/filter/filter.c
base/src/intermediate/joinflows/joinflows_ip.c
base/src/intermediate/odip/odip.c
base/src/ipfix_message.c
base/src/preprocessor.c
base/src/storage/forwarding/forwarding.c
plugins/input/nfdump/nfinput.c

Several variables in `storage.h` were referring to 'records' while they should actually refer to 'sets':
* `MSG_MAX_TEMPLATES` > `MSG_MAX_TEMPL_SETS`
* `MSG_MAX_OTEMPLATES` > `MSG_MAX_OPT_TEMPL_SETS`
* `data_records_count` > `data_sets_count`
* `templ_records_count` > `templ_sets_count`
* `opt_templ_records_count` > `opt_templ_sets_count`

Fixed incorrect variable names

---

base/src/intermediate/anonymization/anonymization_ip.c
base/src/ipfix_message.c

The contributions of this pull request can be summarized as follows:
* Fixed a bug in `get_data_records` (`ipfix_message.c`) that caused the function to always return only the first data record (index: 0) of the dataset. This caused the anonymization plugin to always anonymize the first data record only.
* Anonymization plugin now allows for explicit key definition in `startup.xml` with `key` element.
* Many minor improvements (syntax improvements, memory leak fixes, etc.) in anonymization plugin.

Improvements to anonymization intermediate plugin

---

base/headers/ipfixcol/templates.h
base/src/ipfix_message.c
base/src/template_manager.c

The use of `template_contains_field` is rather cumbersome:
* The name of the method suggests it to return a boolean-typed variable, while it (nowadays) returns a field offset.
* When using it for enterprise-specific fields, one has to guess (or check the source code) that the enterprise bit must be set to 1 in the `field` argument.
* In case there are multiple enterprise-specific fields, from different enterprises, with the same field ID, this method returns the wrong offset.
Since there is quite some code that relies on `template_contains_field` (for obtaining field offsets based on templates) I decided to not touch that function, but create a new function that does the right job. This new function, `template_get_field_offset`, takes also an enterprise ID and considers it when finding …

Template manager: implemented template_get_field_offset

---

base/headers/ipfixcol/input.h
base/src/configurator.c
base/src/data_manager.c
base/src/output_manager.c
base/src/output_manager.h
base/src/preprocessor.c

This is a first refactoring round for the data record and loss management within the Output Manager. The old implementation was not able to deal with simultaneous ODIDs, among others. Some corner cases still have to be fixed, but this should already be a major improvement.

Output Manager: refactored statistics management

---

plugins/storage/fastbit/fastbit.cpp
plugins/storage/fastbit/fastbit_element.cpp
plugins/storage/fastbit/fastbit_element.h
plugins/storage/fastbit/fastbit_table.cpp
plugins/storage/fastbit/fastbit_table.h

Although caused by another bug (fixed in CESNET/devel already), we have seen data with enterprise ID '-1'. To avoid such issues, enterprise and field IDs are now properly declared using `uint_t` data structures instead of regular integers.

FastBit storage: data types for enterprise and field IDs are now declared more precisely

---

base/src/ipfixcol.c
base/src/output_manager.c

In addition, statistics are not printed to stdout if statistics files are used. This is to avoid duplicate information and log files being spammed on production systems.

Output Manager: cleanup of statistics files

---

tools/fbitmerge/src/fbitmerge.cpp
tools/fbitmerge/src/fbitmerge.h

A little background on this code change: we were encountering some strange behavior of fbitmerge that caused the values in `std::map<uint32_t, char *> dirMap` (fbitmerge.cpp:564) to become corrupted at some point in time. This issue occurred every day in our daylong datasets, causing the merge process to fail. This pull request resolves this issue and should not affect functionality.

fbitmerge: refactored to use std::string instead of c_str()

---

tools/fbitmerge/src/fbitmerge.cpp

We have seen a crash of fbitmerge with the following output:
```
terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::substr
```
Although the data that was merged at that moment was already removed before we could analyze the problem in detail, we suspect the problem to be in one of the 'fixed' lines. This fix will avoid crashes in the future and log an appropriate error message.

fbitmerge: improved stability when encountering unexpected directory names

---

base/src/input/sctp/sctp_input.c
base/src/input/tcp/tcp_input.c
base/src/input/udp/udp_input.c
base/src/ipfixcol.c

Avoids duplicate logging, especially upon receiving non-NetFlow and non-IPFIX traffic on the listening ports.

Input plugin logging consistency fixes

---

base/src/input/sctp/convert.c
base/src/input/sctp/convert.h
base/src/input/sctp/sctp_input.c
base/src/input/tcp/convert.c
base/src/input/tcp/convert.h
base/src/input/tcp/tcp_input.c
base/src/input/udp/convert.c
base/src/input/udp/convert.h
base/src/input/udp/udp_input.c
base/src/ipfix_message.c

Added some sanity checks in PDU conversion code, to avoid SEGFAULTS as a consequence of non-NetFlow and non-IPFIX PDUs getting to the NFv9 conversion code. This could happen if two bytes in those PDUs at the offset of the NetFlow/IPFIX version number carried a value of '9'. I have added some sanity checks that causes the conversion to fail/stop in case of strange combinations of values. Also, I made many code consistency improvements.

Sanity checks in PDU conversion code

---

base/src/output_manager.c

To avoid confusion about the mode in which the Output Manager is run, the mode is logged upon Output Manager creation and mode change (logging level 'notice').

Output manager improvements

---

base/src/output_manager.c

The ODID for the output queue is somewhat misleading when the OM is run in Single Manager mode. I therefore changed it behavior such that the ODID is not printed for the output queue if the OM is run in Single Manager mode.

Improve OM statistics logging when run in Single Manager mode

---

plugins/storage/lnfstore/configure.ac

lnfstore.c: In function 'store_packet':
lnfstore.c:133:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
for(int i = 0; i < ipfix_msg->data_records_count; i++)
^
lnfstore.c:133:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Makefile:489: recipe for target 'lnfstore.lo' failed

compile option required

---

base/headers/ipfixcol/ipfix_message.h
base/headers/ipfixcol/templates.h
base/src/ipfix_message.c
base/src/template_manager.c

The main purpose of this pull request is to start adding support for multi-instanced fields, i.e., multiple instances of the same field per template/data record. For example, the following methods were added:
* `template_record_count_field_occurences`: count number of instances of a particular field in a data record.
* `data_record_field_next_offset`: get offset of next field's instance. Note that `data_record_field_next_offset` is actually a generalization of the existing method `data_record_field_offset`. Compatibility with existing code should remain.
Includes various semantic and coding improvements as well.

Preparations for multi-instanced fields

---

base/src/intermediate/filter/filter.c
base/src/ipfixviewer/ipfixcol-ipfixviewer-output.c
base/src/output_manager.c
base/src/utils/profiles/filter.c

-fixes based on GCC warnings on 32bit ARMv7
-long int was too small for integer constant on 32bit architecture
-exact-width integer types have to be coverted using macros defined in
inttypes.h (PRIu64, PRIx32, ...)

Portability fix: data types and data type conversions

---

base/documentation/man/ipfixcol.dbk
base/src/ipfixcol.c
plugins/storage/lnfstore/ipfixcol-lnfstore-output.dbk
plugins/storage/lnfstore/lnfstore.c

New argument option -p FILE will cause creation of FILE with all PIDs
written in it in a textual representation separated by new line. This
FILE will be deleted (unlinked) during termination.

IPFIXcol: add support for pidfile

---

tools/fbitdump/src/Printer.cpp
tools/fbitdump/src/plugins/plugin_header.h

Fbitdump plugins should now have access to variable length / string IE.

fbitdump: add text IE to arg for plugins

---

plugins/storage/fastbit/config_struct.h
plugins/storage/fastbit/fastbit.cpp
plugins/storage/fastbit/fastbit.h
plugins/storage/fastbit/fastbit_element.cpp
plugins/storage/fastbit/fastbit_element.h
plugins/storage/fastbit/fastbit_table.cpp
plugins/storage/fastbit/ipfixcol-fastbit-output.dbk

This feature certainly needs some more testing, but we are providing it already to you for review. If no changes are made to `startup.xml`, the FastBit plugin should work just like before.

FastBit storage: Support for using ipfix-elements.xml data lengths instead of template lengths

---

base/src/utils/conversion/convert.c

The problem was in de `while`-condition that loops over the various template records. Since `template_row` was only increased just after the condition was evaluated, the condition was actually flawed and resulted in memory errors (and SEGFAULT).

Fix SEGFAULT in NFv9 options template conversion code

---

base/src/preprocessor.c

So far, only the ODID was used for the unique identification of a data source for template management. The new code also considers the exporter IP address (and connected port number).
Please perform a careful code review!

preprocessor: use full data source for template management 

---

plugins/storage/json/README.md
plugins/storage/json/ipfixcol-json-output.dbk
plugins/storage/json/json.cpp
plugins/storage/json/json.h

s/formated/formatted/ in json storage plugin config and manpage. Backwards compatible with old spelling.

Typo fix in json plugin

---

base/src/input/tcp/tcp_input.c
base/src/queues.c
base/src/queues.h
base/src/utils/libsiso/siso.h

There is also a major issue found while working on the last commit.  Maybe a larger patch to fix the duplication of doc-comments between header and `.c` is needed.

Minor typos in doc-comments and Doxygen warnings
