base/src/config.c
base/src/data_manager.c
base/src/input/ipfix/ipfix_file.c
base/src/input/tcp/tcp_input.c
base/src/input/udp/sflow.c
base/src/intermediate/filter/filter.c
base/src/intermediate/joinflows/joinflows_ip.c
base/src/intermediate/odip/odip.c
base/src/preprocessor.c
base/src/queues.c
base/src/storage/forwarding/forwarding.c
base/src/utils/ipfixsend/reader.c
base/src/utils/utils.c

This pull request features a long list of vulnerability fixes and is complementary to pull request #19. In case of merging problems, please let me know.

Bunch of vulnerability fixes

---

base/src/data_manager.c
base/src/input/ipfix/ipfix_file.c
base/src/input/sctp/sctp_input.c
base/src/input/sctp/sflow.c
base/src/input/sctp/sflow.h
base/src/input/tcp/sflow.c
base/src/input/tcp/sflow.h
base/src/input/tcp/tcp_input.c
base/src/input/udp/sflow.c
base/src/input/udp/sflow.h
base/src/input/udp/udp_input.c
base/src/intermediate/filter/filter.c
base/src/ipfixcol.c
base/src/output_manager.c
base/src/preprocessor.c
base/src/queues.c
base/src/storage/forwarding/forwarding.c
base/src/template_manager.c
base/src/utils/ipfixsend/reader.c
base/src/utils/utils.c
plugins/storage/fastbit/fastbit.cpp
plugins/storage/fastbit/fastbit_element.cpp

This pull request features a long list of vulnerability fixes and is complementary to pull request #19 and #20. In case of merging problems, please let me know.

Another bunch of vulnerability fixes

---

base/src/config.c
base/src/input/sctp/convert.c
base/src/input/sctp/sflow.c
base/src/input/tcp/convert.c
base/src/input/udp/convert.c
base/src/template_manager.c
base/src/utils/ipfixsend/ipfixsend.c
base/src/utils/ipfixsend/reader.c

This pull request is complementary to pull request #19, #20 and #22. Please don't hesitate to contact me in case of questions or merging problems.

Stability fixes

---

tools/fbitdump/src/Configuration.cpp
tools/fbitdump/src/Filter.cpp
tools/fbitdump/src/Table.cpp
tools/fbitdump/src/TableManager.cpp
tools/fbitdump/src/TableManagerCursor.cpp
tools/fbitdump/src/Utils.cpp
tools/fbitdump/src/Utils.h

It would be good if you could check the fix in 7e81463. The old code was logically dead, but I'm not quite sure whether the statement should be removed completely, or whether my fix is appropriate.
Please don't hesitate to contact me in case of questions or merging problems.

fbitdump stability and vulnerability fixes (1)

---

base/src/storage/forwarding/forwarding.c

Refactored and simplified forwarding-plugin, as discussed via e-mail with @mikeek.

Refactored forwarding-plugin

---

tools/fbitdump/man/fbitdump.dbk
tools/fbitdump/src/Configuration.cpp

Minor corrections and improvements to the help available by `fbitdump -h` and fbitdump's man-page.

fbitdump: Improved help

---

base/src/input/sctp/sctp_input.c
base/src/input/udp/udp_input.c
base/src/intermediate/hooks/hooks.c
base/src/template_manager.c

Mostly resource leaks and null dereferences.

Various stability fixes

---

base/src/configurator.c
base/src/configurator.h
base/src/input/udp/udp_input.c
base/src/ipfixcol.c

I came across these while hunting for a bug (#67), but since I haven't found the bug yet, I'm already pushing these.

Various indentation fixes

---

Makefile.am
configure.ac
plugins/storage/unirec/configure.ac

Unirec build improvements

---

base/config/internalcfg.xml.template
base/tests/ipfixcol_test/create_internal.sh
base/tests/ipfixcol_test/test.sh
base/tests/ipfixcol_test/tests/basic - one input file/startup.xml
base/tests/ipfixcol_test/tests/ipfixsend - enterprise fields,sctp/startup.xml
base/tests/ipfixcol_test/tests/ipfixsend - two inputs udp/startup.xml
base/tests/ipfixcol_test/tests/one input + forwarding/startup.xml

Both bug fixes and syntactical improvements.

Various improvements to test suite (2)

---

tools/fbitdump/src/Configuration.cpp
tools/fbitdump/src/fbitdump.cpp
tools/fbitexpire/src/fbitexpire.cpp

fbitdump, fbitexpire: implemented longopt support

---

tools/fbitdump/src/plugins/dns_rcode.c
tools/fbitdump/src/plugins/http_status_code.c
tools/fbitdump/src/plugins/httprt.c
tools/fbitdump/src/plugins/mac.c
tools/fbitdump/src/plugins/sip_method.c
tools/fbitdump/src/plugins/smtp_command.c
tools/fbitdump/src/plugins/smtp_statuscode.c
tools/fbitdump/src/plugins/tls_csuites.c
tools/fbitdump/src/plugins/tls_csuites_array.c
tools/fbitdump/src/plugins/tls_version.c
tools/fbitdump/src/plugins/voip_rtpcodec.c
tools/fbitdump/src/plugins/voip_type.c

Many compilation warnings are fixed, as well as stylistic code inconsistencies (compared to other fbitdump/IPFIXcol code).
Please double-check the modifications in this commit before merging.

fbitdump plugins: fixed many compilation errors and stylistic problems

---

base/src/input/sctp/convert.c
base/src/input/tcp/convert.c
base/src/input/udp/convert.c

Fixes the issues described in #91, i.e., inserts padding for sets that are not 4-byte aligned. The real modifications are in line 586-594.

Fixed padding problem in NFv9 > IPFIX conversion

---

plugins/input/nfdump/nfinput.c
plugins/input/nfdump/nfinput.h

* Fixes compiler error due to some error in previous merging
* Fixes several compiler warnings

Several nfinput input plugin fixes

---

base/src/storage/forwarding/forwarding.c

The discovered bug caused all IPFIX messages with template sets to feature a data corruption at byte offset 178 from the IPFIX message header. This was caused by the following statement:
```
((struct ipfix_template_set *) proc.msg + prevo)->header.length = htons(proc.length);
```
This statement should actually be as follows:
```
((struct ipfix_template_set *) (proc.msg + prevo))->header.length = htons(proc.length);
```
I've taken the opportunity to make the code a bit simpler and easier to read.

Forwarding storage: fixed data corruption in template sets

---

base/src/utils/utils.c
tools/fbitdump/Makefile.am
tools/fbitdump/fbitdump.xml.template
tools/fbitdump/man/fbitdump.dbk
tools/fbitdump/src/Column.h
tools/fbitdump/src/Configuration.cpp
tools/fbitdump/src/Configuration.h.in
tools/fbitdump/src/Printer.cpp
tools/fbitdump/src/Utils.cpp
tools/fbitdump/src/fbitdump.cpp

For the various components of this pull requests, please check the individual commits.

fbitdump stability and usability fixes

---

base/src/input/sctp/convert.c
base/src/input/sctp/convert.h
base/src/input/sctp/sctp_input.c
base/src/input/tcp/convert.c
base/src/input/tcp/convert.h
base/src/input/tcp/tcp_input.c
base/src/input/udp/convert.c
base/src/input/udp/convert.h
base/src/input/udp/udp_input.c
base/src/ipfixcol.c
base/src/preprocessor.c

Various fixes and improvements to improve stability of input plugins and IPFIXcol in general, especially in cases where malicious packets are sent to IPFIXcol.

Input stability fixes and improvements

---

base/src/input/sctp/convert.c
base/src/input/tcp/convert.c
base/src/input/udp/convert.c
base/src/ipfix_message.c
base/src/preprocessor.c
base/src/storage/forwarding/forwarding.c
base/src/template_manager.c

Main contributions are in 05e5d59 and baf02c4.

Fixes to improve options template support

---

tools/fbitmerge/src/fbitmerge.cpp

Merged folders now get mtime of latest mtime of subfolders. This can be advantageous for automated processing of (merged) FastBit data.

fbitmerge: set mtime of merge destination folder back in time

---

plugins/storage/fastbit/fastbit.cpp
plugins/storage/fastbit/fastbit_element.cpp
plugins/storage/fastbit/fastbit_table.cpp

Many errors would be logged twice, resulting in flooded log files.

Fastbit storage: removed duplicate logging in case of errors

---

base/src/output_manager.c

Also used the opportunity to slightly refactor some recent modifications in the statistics thread.

Output Manager / statistics: fixed printing orphan characters to statistics file

---

tools/fbitmerge/src/fbitmerge.cpp
tools/fbitmerge/src/fbitmerge.h

Also made some coding style consistency improvements, to make the coding style of fbitmerge more consistent with the other IPFIXcol project components.

fbitmerge: fixed use of invalid operators in C++ maps

---

base/config/startup.xml
base/headers/ipfixcol/storage.h
base/src/configurator.c
base/src/intermediate/odip/odip.c
base/src/intermediate_process.c
base/src/ipfix_message.c
base/src/output_manager.c
base/src/queues.c
base/src/queues.h

Mostly related to consistency and readability

Various code improvements

---

coding_style.md

Should be nothing new in here. Nevertheless, it may help when others are contributing code.

Coding style guideline extension

---

plugins/storage/fastbit/config_struct.h
plugins/storage/fastbit/fastbit.cpp
plugins/storage/fastbit/fastbit.h
plugins/storage/fastbit/fastbit_element.cpp
plugins/storage/fastbit/fastbit_element.h
plugins/storage/fastbit/fastbit_table.cpp
plugins/storage/fastbit/fastbit_table.h
plugins/storage/fastbit/ipfixcol-fastbit-output.dbk

This functionality is only enabled once specified in IPFIXcol's startup configuation:
```xml
<fileWriter>
<fileFormat>fastbit</fileFormat>
...
<createSpFiles>yes</createSpFiles>
...
</fileWriter>
```

FastBit storage: Write .sp files for TEXT columns

---

base/src/preprocessor.c

Only print a warning message if this is not the first message, since the first message always triggers an alert (sequence number is then compared to zero) when a trace is replayed. The impact for live flow data feeds is very limited, since this fix *could* only prohibit the logging of a warning if the first IPFIX message features a sequence number error.

Preprocessor: don't print seq. error warning for first received packet

---

plugins/storage/postgres/postgres_output.c

storage_postgres: fix initialization conf->table_names by zero

storage_postgres: Update postgres_output.c

---

plugins/storage/fastbit/config_struct.h
plugins/storage/fastbit/fastbit.cpp

In addition, this pull request features a fix for two invalid debug log messages.

Fastbit storage: fix static exporter IP address in od_infos

---

tools/fbitdump/src/Configuration.cpp
tools/fbitdump/src/TableManager.cpp
tools/fbitdump/src/Utils.cpp

No functional changes have been introduced.

fbitdump: various minor improvements

---

base/src/utils/filter/filter_wrapper.c

Some lines are just to tidy up the code

Fixed bad behaviour of constants
